added Sorting algorithms using Recursion
N0vice17/DataStructures-And-Algorithm pull request #75
Opened 2023-10-06 06:34 UTC by Rohit-Kavitake

2023-10-06 18:06 UTC, Agnik7 requested changes

2023-10-06 18:06 UTC, Agnik7 commented on Sorting Algorithms (Recursion)/LinearSearch.cpp
> +void print(int arr[], int n) {
This `print` method is unnecessary to the code, so it would be better to remove it.

2023-10-07 06:34 UTC, Rohit-Kavitake commented
I have done the required changes, Please Merge

2023-10-07 09:07 UTC, Agnik7 approved these changes

2023-10-07 09:07 UTC, merged