Implemented stack using queue and queue using stack in python
N0vice17/DataStructures-And-Algorithm pull request #94
Opened 2023-10-11 06:52 UTC by Sreeram0303

Added a new sub folder under stack folder named python

2023-10-12 15:40 UTC, IndranjanaChatterjee commented
@Sreeram0303  ,reviewed your pull request, and  noticed that you referenced using a queue from the collections module in Python. However, I want to bring to your attention that Python's collections module does not include a queue implementation.

[REFERENCE LINK](https://docs.python.org/3/library/collections.html)

2023-10-12 15:46 UTC, IndranjanaChatterjee requested changes
@Sreeram0303  ,reviewed your pull request, and  noticed that you referenced using a queue from the collections module in Python. However, I want to bring to your attention that Python's collections module does not include a queue implementation.

[REFERENCE LINK](https://docs.python.org/3/library/collections.html)

2023-10-12 16:30 UTC, Sreeram0303 commented
HI @IndranjanaChatterjee thanks for pointing out my mistake and now i corrected the wrong import

2023-10-14 03:20 UTC, IndranjanaChatterjee approved these changes

2023-10-14 03:20 UTC, merged